POST http://localhost:3000/login
Content-Type: application/json

{ "nama": "ar", "email": "email" }


###

GET  http://localhost:3000/dasboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1hIjoiYXIiLCJlbWFpbCI6ImVtYWlsIiwiaWF0IjoxNzU5NTkyODM5LCJleHAiOjE3NTk1OTI4Nzl9.JFiuvD7Y-1jsE9hYGMUml5FDO0QPvAsTOYZmKawXUfQ
refreshToken: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1hIjoiYXIiLCJlbWFpbCI6ImVtYWlsIiwiaWF0IjoxNzU5NTkyNzY3LCJleHAiOjE3NjAxOTc1Njd9.ZW7qbQLnAOarUw-ifSHfVT05T1XguraswdliOFmpdMU