// USER

// sign in
# POST http://localhost:3000/auth/signin
# Content-Type: application/json

#  {  "email": "budi@example.com", password": "budi123" }

###

// sign up
# POST   http://localhost:3000/auth/signup
# Content-Type: application/json

# { "name": "Ahmad",  "email": "ahmad@example.com",  "password": "ahmad123" }

###

// ADMIN

# POST   http://localhost:3000/auth/signin
# Content-Type: application/json

#  { "email": "ar.gmail.com", "name": "ar","password": "ararar1234" }

###

// admin
GET  http://localhost:3000/api/admin/users
# GET  http://localhost:3000/api/admin/users/68e760dfe95802772e1512f0
# PATCH   http://localhost:3000/api/admin/users/68e763bc0137ff82e495dfbe/role
# DELETE    http://localhost:3000/api/admin/users/68e763bc0137ff82e495dfbe
# GET  http://localhost:3000/api/admin/users/68e7642d0137ff82e495dfbf/notes
# GET  http://localhost:3000/api/admin/notes/68e781be604b48045db6029e
# GET  http://localhost:3000/api/admin/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGUyNDBlZDVhY2I5MmU4YzZjZWJlYTQiLCJlbWFpbCI6ImFyLmdtYWlsLmNvbSIsInJvbGUiOiJzdXBlciBhZG1pbiIsIm5hbWUiOiJhciIsInBhc3N3b3JkIjoiYXJhcmFyMTIzNCIsImlhdCI6MTc1OTk5NDExMSwiZXhwIjoxNzYwMDgwNTExfQ.2Ximf-p3taspfJGaWBdBPcJoZ8wKPuoH9EpEZW7EtcQ
refreshToken: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OGUyNDBlZDVhY2I5MmU4YzZjZWJlYTQiLCJlbWFpbCI6ImFyLmdtYWlsLmNvbSIsInJvbGUiOiJzdXBlciBhZG1pbiIsIm5hbWUiOiJhciIsInBhc3N3b3JkIjoiYXJhcmFyMTIzNCIsImlhdCI6MTc1OTk5NDExMSwiZXhwIjoxNzYwNTk4OTExfQ.J0XwWetFF6Raoj98IixIs1W60iQ_TNM_n9Ogw820f1w
# Content-Type: application/json

# {"role" : "user"}

###

// user
# GET  http://localhost:3000/api/user/68e777ec0e7bccbe66e75a0f
# DELETE   http://localhost:3000/api/user/68e7699b79c657d6c44170f8

// note
# GET  http://localhost:3000/api/note/notes
# GET  http://localhost:3000/api/note/notes/68e7818b604b48045db6029d
POST http://localhost:3000/api/note/notes/add
# PATCH http://localhost:3000/api/note/notes/update
# DELETE http://localhost:3000/api/note/notes/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTBjMjdmYTVjMDg2YWE2MTdhYThjOGUiLCJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiYnVkaSIsImVtYWlsIjoiYnVkaUBnbWFpbC5jb20iLCJhdmF0YXIiOiJhdmF0YXItMSIsImlhdCI6MTc2MzI5NDQ4MywiZXhwIjoxNzYzMjk4MDgzfQ.0Jq7EeTtZZKkQR3OIAB5Xc3o9E2ROBh1coxgf0svuqM
refreshToken: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OTBjMjdmYTVjMDg2YWE2MTdhYThjOGUiLCJyb2xlIjoidXNlciIsInVzZXJuYW1lIjoiYnVkaSIsImVtYWlsIjoiYnVkaUBnbWFpbC5jb20iLCJhdmF0YXIiOiJhdmF0YXItMSIsImlhdCI6MTc2MzI4OTU5NCwiZXhwIjoxNzYzODk0Mzk0fQ.MJv4-GDt1H6_Mc25WkSgVtfzIKgU1W9-yyXG5fKMpJM
Content-Type: application/json

{
  "judul": "Reflection Night",
  "isi": "Think about what went well and what can be improved.",
  "archive": false,
  "favorite": false,
  "pinned": true,
  "tag": "Thoughts & Mood",
  "color": "#F5DEB3",
  "createdAt": "2025-10-01T21:00:00.000Z",
  "updatedAt": "2025-10-01T21:00:00.000Z"
}











###





